server:
  port: 8090

spring:
  application:
    name: producto-back

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    #healthcheck:
     # enabled: true
      
#management:
#  endpoint:
#    health:#      enabled: true
#management:
 # server:
  #  port: 9001
   # address: localhost
          