server:
  port: 8091

spring:
  application:
    name: hystrix-service
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream