server:
  port: 8092

spring:
  application:
    name: ribbon-client

ribbon-test:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8090,localhost:8050,localhost:8051
    ServerListRefreshInterval: 15000